//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPedidos.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosPedidos
    {
        public int Id_productosPedido { get; set; }
        public int FIdPedido { get; set; }
        public int FIdProducto { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
