//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPedidos.Clases
{
    using System;
    using System.Collections.Generic;

    public partial class Productos
    {
        public int Id_prod { get; set; }
        public string Nombre_prod { get; set; }
        public int FidFamilia { get; set; }
        public decimal Precio { get; set; }

        //public string NombreFamilia { get; set; }

        public virtual Familia Familia { get; set; }

    }
}
