//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPedidos.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        public int Id_Restaurante { get; set; }
        public string Restaurante { get; set; }
    }
}
